# Generated by Django 2.1.2 on 2018-10-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('water_level', models.IntegerField()),
                ('rain_audio_level', models.FloatField()),
                ('is_raining', models.BooleanField()),
            ],
        ),
    ]
